/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type {
  AuthLogout200,
  AuthSendOTP200,
  AuthSendOTPBody,
  AuthVerifyOTP200,
  AuthVerifyOTP400,
  AuthVerifyOTPBody,
  MeGetMe200,
  MeGetMe401,
} from "./model";

export type authSendOTPResponse200 = {
  data: AuthSendOTP200;
  status: 200;
};

export type authSendOTPResponseSuccess = authSendOTPResponse200 & {
  headers: Headers;
};
export type authSendOTPResponse = authSendOTPResponseSuccess;

export const getAuthSendOTPUrl = () => {
  return `https://template-lemon-nine.vercel.app/api/auth/send-otp`;
};

export const authSendOTP = async (
  authSendOTPBody: AuthSendOTPBody,
  options?: RequestInit,
): Promise<authSendOTPResponse> => {
  const res = await fetch(getAuthSendOTPUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authSendOTPBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authSendOTPResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authSendOTPResponse;
};

export type authVerifyOTPResponse200 = {
  data: AuthVerifyOTP200;
  status: 200;
};

export type authVerifyOTPResponse400 = {
  data: AuthVerifyOTP400;
  status: 400;
};

export type authVerifyOTPResponseSuccess = authVerifyOTPResponse200 & {
  headers: Headers;
};
export type authVerifyOTPResponseError = authVerifyOTPResponse400 & {
  headers: Headers;
};

export type authVerifyOTPResponse =
  | authVerifyOTPResponseSuccess
  | authVerifyOTPResponseError;

export const getAuthVerifyOTPUrl = () => {
  return `https://template-lemon-nine.vercel.app/api/auth/verify-otp`;
};

export const authVerifyOTP = async (
  authVerifyOTPBody: AuthVerifyOTPBody,
  options?: RequestInit,
): Promise<authVerifyOTPResponse> => {
  const res = await fetch(getAuthVerifyOTPUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authVerifyOTPBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authVerifyOTPResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authVerifyOTPResponse;
};

export type authLogoutResponse200 = {
  data: AuthLogout200;
  status: 200;
};

export type authLogoutResponseSuccess = authLogoutResponse200 & {
  headers: Headers;
};
export type authLogoutResponse = authLogoutResponseSuccess;

export const getAuthLogoutUrl = () => {
  return `/auth/logout`;
};

export const authLogout = async (
  options?: RequestInit,
): Promise<authLogoutResponse> => {
  const res = await fetch(getAuthLogoutUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLogoutResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authLogoutResponse;
};

export type meGetMeResponse200 = {
  data: MeGetMe200;
  status: 200;
};

export type meGetMeResponse401 = {
  data: MeGetMe401;
  status: 401;
};

export type meGetMeResponseSuccess = meGetMeResponse200 & {
  headers: Headers;
};
export type meGetMeResponseError = meGetMeResponse401 & {
  headers: Headers;
};

export type meGetMeResponse = meGetMeResponseSuccess | meGetMeResponseError;

export const getMeGetMeUrl = () => {
  return `/me`;
};

export const meGetMe = async (
  options?: RequestInit,
): Promise<meGetMeResponse> => {
  const res = await fetch(getMeGetMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: meGetMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as meGetMeResponse;
};
