/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */

export type AuthVerifyOTP400OneOf = {
  defined: "true";
  code: "INVALID_OTP";
  status: "400";
  message: string;
  data?: unknown;
};
