/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */

export type AuthVerifyOTP400OneOfTwo = {
  defined: unknown;
  code: string;
  status: number;
  message: string;
  data?: unknown;
};
