/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { AuthVerifyOTP400OneOf } from "./authVerifyOTP400OneOf";
import type { AuthVerifyOTP400OneOfTwo } from "./authVerifyOTP400OneOfTwo";

export type AuthVerifyOTP400 = AuthVerifyOTP400OneOf | AuthVerifyOTP400OneOfTwo;
