/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */

export type AuthVerifyOTPBody = {
  email: string;
  /**
   * @minLength 6
   * @maxLength 6
   */
  code: string;
};
