/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfo } from "./meGetMe200SessionUserWithInfo";

export type MeGetMe200Session = {
  id: string;
  userWithInfo: MeGetMe200SessionUserWithInfo;
  createdAt: string;
  lastVerifiedAt: string;
};
