/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfoTransporterAnyOf } from "./meGetMe200SessionUserWithInfoTransporterAnyOf";

export type MeGetMe200SessionUserWithInfoTransporter =
  MeGetMe200SessionUserWithInfoTransporterAnyOf | null;
