/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfoProducerAnyOf } from "./meGetMe200SessionUserWithInfoProducerAnyOf";

export type MeGetMe200SessionUserWithInfoProducer =
  MeGetMe200SessionUserWithInfoProducerAnyOf | null;
