/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe401OneOf } from "./meGetMe401OneOf";
import type { MeGetMe401OneOfTwo } from "./meGetMe401OneOfTwo";

export type MeGetMe401 = MeGetMe401OneOf | MeGetMe401OneOfTwo;
