/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */

export type MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType =
  (typeof MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType)[keyof typeof MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType = {
  CAR: "CAR",
  MOTORCYCLE: "MOTORCYCLE",
  TRUCK: "TRUCK",
  VAN: "VAN",
  REFRIGERATED_TRUCK: "REFRIGERATED_TRUCK",
  REFRIGERATED_VAN: "REFRIGERATED_VAN",
} as const;
