/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */

export type MeGetMe200SessionUserWithInfoProducerAnyOf = {
  wilayaId: number;
  cityId: number;
  address: string;
  farmerLicenseNumber: string;
};
