/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200Session } from "./meGetMe200Session";

export type MeGetMe200 = {
  session: MeGetMe200Session;
};
