/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfoFullname } from "./meGetMe200SessionUserWithInfoFullname";
import type { MeGetMe200SessionUserWithInfoPhone } from "./meGetMe200SessionUserWithInfoPhone";
import type { MeGetMe200SessionUserWithInfoRole } from "./meGetMe200SessionUserWithInfoRole";
import type { MeGetMe200SessionUserWithInfoProducer } from "./meGetMe200SessionUserWithInfoProducer";
import type { MeGetMe200SessionUserWithInfoTransporter } from "./meGetMe200SessionUserWithInfoTransporter";
import type { MeGetMe200SessionUserWithInfoBuyer } from "./meGetMe200SessionUserWithInfoBuyer";

export type MeGetMe200SessionUserWithInfo = {
  id: string;
  email: string;
  fullname: MeGetMe200SessionUserWithInfoFullname;
  phone: MeGetMe200SessionUserWithInfoPhone;
  role: MeGetMe200SessionUserWithInfoRole;
  producer: MeGetMe200SessionUserWithInfoProducer;
  transporter: MeGetMe200SessionUserWithInfoTransporter;
  buyer: MeGetMe200SessionUserWithInfoBuyer;
  createdAt: string;
  updatedAt: string;
};
