/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType } from "./meGetMe200SessionUserWithInfoTransporterAnyOfVehicleType";
import type { MeGetMe200SessionUserWithInfoTransporterAnyOfVehiclePhoto } from "./meGetMe200SessionUserWithInfoTransporterAnyOfVehiclePhoto";

export type MeGetMe200SessionUserWithInfoTransporterAnyOf = {
  licenseNumber: string;
  plateNumber: string;
  vehicleType: MeGetMe200SessionUserWithInfoTransporterAnyOfVehicleType;
  loadCapacityInKg: number;
  vehiclePhoto: MeGetMe200SessionUserWithInfoTransporterAnyOfVehiclePhoto;
};
