/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API Reference
 * OpenAPI spec version: 0.0.0
 */
import type { MeGetMe200SessionUserWithInfoBuyerAnyOf } from "./meGetMe200SessionUserWithInfoBuyerAnyOf";

export type MeGetMe200SessionUserWithInfoBuyer =
  MeGetMe200SessionUserWithInfoBuyerAnyOf | null;
